[package]
name = "moto_auto_db"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
serde = "1.0.216"
sqlx = { version = "0.8.2", features = ["chrono", "postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1.42.0", features = ["full"] }
